=== uncefact/tests-untp/packages/untp-test-suite/src/schemas/digitalIdentityAnchor/v0.2.1/schema.json
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "type": {
      "type": "array",
      "readOnly": true,
      "const": ["DigitalIdentityAnchor", "VerifiableCredential"],
      "default": ["DigitalIdentityAnchor", "VerifiableCredential"],
      "items": {
        "type": "string",
        "enum": ["DigitalIdentityAnchor", "VerifiableCredential"]
      }
    },
    "@context": {
      "example": "https://test.uncefact.org/vocabulary/untp/dpp/dpp-context.jsonld",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["https://www.w3.org/ns/credentials/v2", "https://test.uncefact.org/vocabulary/untp/dia/0.2.1/"]
      },
      "description": "A list of JSON-LD context URIs that define the semantic meaning of properties within the credential. ",
      "readOnly": true,
      "const": ["https://www.w3.org/ns/credentials/v2", "https://test.uncefact.org/vocabulary/untp/dia/0.2.1/"],
      "default": ["https://www.w3.org/ns/credentials/v2", "https://test.uncefact.org/vocabulary/untp/dia/0.2.1/"]
    },
    "id": {
      "example": "did:web:sample-business.com:123456789#90664869327",
      "type": "string",
      "format": "uri",
      "description": "A unique identifier assigned to the identity anchor credential. "
    },
    "issuer": {
      "$ref": "#/$defs/CredentialIssuer",
      "description": "The organisation that is the issuer of this VC. Note that the \"id\" property MUST be a W3C DID.  Other identifiers such as tax registration numbers can be listed in the \"otherIdentifiers\" property."
    },
    "validFrom": {
      "example": "2024-03-15T12:00:00",
      "type": "string",
      "format": "date-time",
      "description": "The date and time from which the credential is valid."
    },
    "validUntil": {
      "example": "2034-03-15T12:00:00",
      "type": "string",
      "format": "date-time",
      "description": "The expiry date (if applicable) of this verifiable credential."
    },
    "credentialSubject": {
      "$ref": "#/$defs/RegisteredIdentity",
      "description": "The registered identity from the authoritative register that is the subject of this credential"
    }
  },
  "description": "The Digital Identity Anchor (DIA) is a very simple credential that is issued by a trusted authority and asserts an equivalence between a member identity as known to the authority (eg a VAT number) and one or more decentralised identifiers (DIDs) held by the member.  ",
  "required": ["@context", "id", "issuer"],
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "CredentialIssuer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "array",
          "readOnly": true,
          "const": ["CredentialIssuer"],
          "default": ["CredentialIssuer"],
          "items": {
            "type": "string",
            "enum": ["CredentialIssuer"]
          }
        },
        "id": {
          "example": "did:web:identifiers.example-company.com:12345",
          "type": "string",
          "format": "uri",
          "description": "The W3C DID of the issuer - should be a did:web or did:tdw"
        },
        "name": {
          "example": "Example Company Pty Ltd",
          "type": "string",
          "description": "The name of the issuer person or organisation"
        },
        "otherIdentifier": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Identifier"
          },
          "description": "An optional list of other registered identifiers for this credential issuer "
        }
      },
      "description": "The issuer party (person or organisation) of a verifiable credential.",
      "required": ["id", "name"]
    },
    "Identifier": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "array",
          "readOnly": true,
          "const": ["Identifier"],
          "default": ["Identifier"],
          "items": {
            "type": "string",
            "enum": ["Identifier"]
          }
        },
        "id": {
          "example": "https://id.gs1.org/01/09520123456788/21/12345",
          "type": "string",
          "format": "uri",
          "description": "The globally unique ID of the entity as a resolvable URL according to ISO 18975. ExamplesProduct - id.gs1.org/01/09520123456788/21/12345  Party - abr.business.gov.au/ABN/View?abn=90664869327. Facility - did:web:facilities.example-company.com:123. "
        },
        "name": {
          "example": "EV battery 300Ah.",
          "type": "string",
          "description": "The registered name of the entity within the identifier scheme.  Examples: product - EV battery 300Ah, Party - Sample Company Pty Ltd,  Facility - Green Acres battery factory"
        },
        "registeredId": {
          "example": "90664869327",
          "type": "string",
          "description": "The registration number (alphanumeric) of the entity within the register. Unique within the register."
        },
        "idScheme": {
          "$ref": "#/$defs/IdentifierScheme",
          "description": "The identifier scheme.  Examples : Product - id.gs1.org/01,  Party - business.gov.au/abn,  Facility - did:web:facilities.acme.com. "
        }
      },
      "description": "The ID and Name of an identified entity such as a product, facility, party, standard, etc.  If the identifier is a W3C DID then the corresponding DID document SHOULD include a serviceEndpoint of type \"IdentityResolver\". If the identifier is not a W3C DID then the id property SHOULD be an identity resolver URL.",
      "required": ["id", "name"]
    },
    "IdentifierScheme": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "array",
          "readOnly": true,
          "const": ["IdentifierScheme"],
          "default": ["IdentifierScheme"],
          "items": {
            "type": "string",
            "enum": ["IdentifierScheme"]
          }
        },
        "id": {
          "example": "https://id.gs1.org/01/",
          "type": "string",
          "format": "uri",
          "description": "The globally unique identifier of the registration scheme. The scheme should be registered and discoverable from vocabulary.uncefact.org/identifierSchemes"
        },
        "name": {
          "example": "Global Trade Identification Number (GTIN)",
          "type": "string",
          "description": "The name of the identifier scheme. "
        }
      },
      "description": "An identifier registration scheme for products, facilities, or organisations. Typically operated by a state, national or global authority."
    },
    "RegisteredIdentity": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "type": {
          "type": "array",
          "readOnly": true,
          "const": ["RegisteredIdentity", "Identifier"],
          "default": ["RegisteredIdentity", "Identifier"],
          "items": {
            "type": "string",
            "enum": ["RegisteredIdentity", "Identifier"]
          }
        },
        "id": {
          "example": "did:web:samplecompany.com/123456789",
          "type": "string",
          "format": "uri",
          "description": "The DID that is controlled by the registered member and is linked to the registeredID through this Identity Anchor credential"
        },
        "name": {
          "example": "Sample business Ltd",
          "type": "string",
          "description": "The registered name of the entity within the identifier scheme.  Examples: product - EV battery 300Ah, Party - Sample Company Pty Ltd,  Facility - Green Acres battery factory"
        },
        "registeredId": {
          "example": "123456789",
          "type": "string",
          "description": "The registration number (alphanumeric) of the entity within the register. Unique within the register."
        },
        "idScheme": {
          "$ref": "#/$defs/IdentifierScheme",
          "description": "The identifier scheme.  Examples : Product - id.gs1.org/01,  Party - business.gov.au/abn,  Facility - did:web:facilities.acme.com. "
        },
        "registerType": {
          "type": "string",
          "enum": ["Product", "Facility", "Business", "Trademark", "Land", "Accreditation"],
          "example": "Product",
          "description": "The thematic purpose of the register - organisations, facilities, products, trademarks, etc"
        },
        "registrationScopeList": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uri"
          },
          "description": "List of URIs the represent the role/scopes of membership for the register. For example [\"https://abr.business.gov.au/Help/EntityTypeDescription?Id=19\"]"
        }
      },
      "description": "The identity anchor is a mapping between a registery member identity and one or more decentralised identifiers owned by the member. It may also list a set of membership scopes.",
      "required": ["id", "name"]
    }
  }
}

=== uncefact/tests-untp/packages/untp-test-suite/credentials/digitalIdentityAnchor/DigitalIdentityAnchor_instance-0.2.1.json
{
  "type": ["DigitalIdentityAnchor", "VerifiableCredential"],
  "@context": ["https://www.w3.org/ns/credentials/v2", "https://test.uncefact.org/vocabulary/untp/dia/0.2.1/"],
  "id": "did:web:sample-business.com:123456789#90664869327",
  "issuer": {
    "type": ["CredentialIssuer"],
    "id": "did:web:identifiers.example-company.com:12345",
    "name": "Example Company Pty Ltd",
    "otherIdentifier": [
      {
        "type": ["Identifier"],
        "id": "https://id.gs1.org/01/09520123456788/21/12345",
        "name": "EV battery 300Ah.",
        "registeredId": "90664869327",
        "idScheme": {
          "type": ["IdentifierScheme"],
          "id": "https://id.gs1.org/01/",
          "name": "Global Trade Identification Number (GTIN)"
        }
      },
      {
        "type": ["Identifier"],
        "id": "https://id.gs1.org/01/09520123456788/21/12345",
        "name": "EV battery 300Ah.",
        "registeredId": "90664869327",
        "idScheme": {
          "type": ["IdentifierScheme"],
          "id": "https://id.gs1.org/01/",
          "name": "Global Trade Identification Number (GTIN)"
        }
      }
    ]
  },
  "validFrom": "2024-03-15T12:00:00",
  "validUntil": "2034-03-15T12:00:00",
  "credentialSubject": {
    "type": ["RegisteredIdentity", "Identifier"],
    "id": "did:web:samplecompany.com/123456789",
    "name": "Sample business Ltd",
    "registeredId": "123456789",
    "idScheme": {
      "type": ["IdentifierScheme"],
      "id": "https://id.gs1.org/01/",
      "name": "Global Trade Identification Number (GTIN)"
    },
    "registerType": "Business",
    "registrationScopeList": ["https://jargon.sh", "https://jargon.sh"]
  }
}
